# Generated by Django 5.1.1 on 2024-10-04 16:28

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("style_guide", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picoblockspage",
            name="body",
            field=wagtail.fields.StreamField(
                [("paragraph", 0), ("table", 1)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    1: (
                        "wagtail.contrib.table_block.blocks.TableBlock",
                        (),
                        {"required": False, "table_options": {"minSpareRows": 0}},
                    ),
                },
            ),
        ),
    ]
