# Generated by Django 5.1.1 on 2024-10-04 16:36

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("style_guide", "0003_alter_picoblockspage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picoblockspage",
            name="body",
            field=wagtail.fields.StreamField(
                [("paragraph", 0), ("table", 1), ("image", 2), ("embed", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    1: (
                        "wagtail.contrib.table_block.blocks.TableBlock",
                        (),
                        {"required": False, "table_options": {"minSpareRows": 0}},
                    ),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    3: ("wagtail.embeds.blocks.EmbedBlock", (), {}),
                },
            ),
        ),
    ]
